# Generated by Django 4.1.7 on 2023-02-20 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pic/')),
                ('stall_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('fname', models.CharField(blank=True, max_length=50, null=True)),
                ('lname', models.CharField(blank=True, max_length=50, null=True)),
                ('bday', models.DateField(blank=True, null=True)),
                ('brgy', models.CharField(blank=True, max_length=50, null=True)),
                ('full_address', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery_address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(default=None, null=True)),
                ('rating', models.IntegerField(default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='webpage.customer')),
            ],
        ),
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, max_length=50)),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product_name', models.CharField(blank=True, max_length=50, null=True)),
                ('product_price', models.IntegerField()),
                ('stocks', models.IntegerField()),
                ('stall_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField()),
                ('total_orders', models.IntegerField(default=0)),
                ('estimated_time', models.IntegerField()),
                ('date_ordered', models.DateTimeField()),
                ('order_id', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.customer')),
                ('shop_owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AddedToCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_of_items', models.IntegerField(default=0)),
                ('is_pending', models.BooleanField(default=True)),
                ('is_selected', models.BooleanField(default=False)),
                ('is_ordered', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField()),
                ('cart_id', models.CharField(default=None, max_length=255)),
                ('order_id', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpage.productlist')),
            ],
        ),
    ]
