# Generated by Django 4.1.6 on 2023-02-10 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0028_review_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=None),
        ),
    ]
