# Generated by Django 4.1.6 on 2023-02-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0030_alter_review_rating_alter_review_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addedtocart',
            options={'verbose_name_plural': 'Customer Cart'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Foodhub Customers'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='productlist',
            options={'verbose_name_plural': 'Foodhub Product List'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name_plural': 'Reviews'},
        ),
    ]
