# Generated by Django 4.1.6 on 2023-02-13 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webpage', '0031_alter_addedtocart_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='addedtocart',
            options={'verbose_name_plural': 'Cart'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='productlist',
            options={'verbose_name_plural': 'Product List'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={},
        ),
    ]
